In [34]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [35]:
import numpy as pd
matriks_34 = ("aku memiliki sebuah matriks,yaitu")
print(matriks_34)
a = [
    [2,4,6,10,12],
    [3,7,8,11,13,15],
    [5,9,22,33,37,25],
    [7,22,55,21,13]
]
for isi in a:
    print(isi)
a = pd.array
 

aku memiliki sebuah matriks,yaitu
[2, 4, 6, 10, 12]
[3, 7, 8, 11, 13, 15]
[5, 9, 22, 33, 37, 25]
[7, 22, 55, 21, 13]


In [36]:
import numpy as np
a_34 = np.array((
               [12,10,4],
               [7,4,6]
))
print('matriks a_34 dengan ukuran:',a_34.shape)
print(a_34)
print('matriks a_34 dengan ukuran:',a_34.ndim)
print(a_34)
a_34[1,0] = 20
print(a_34)
   

matriks a_34 dengan ukuran: (2, 3)
[[12 10  4]
 [ 7  4  6]]
matriks a_34 dengan ukuran: 2
[[12 10  4]
 [ 7  4  6]]
[[12 10  4]
 [20  4  6]]


In [50]:
a_34 = [[7,0,0,4,5],
        [2,6,0,1,4],
        [12,3,6,9,0],
        [4,3,6,7,9],
        [9,4,7,2,3]
       ]
a_34 = np.zeros((5,5))
print(a_34)
b_34 = np.identity(5)
print(b_34)
c_34 = 9*b_34
print(c_34)
d_34 = np.ones((4,4))
e_34 = np.identity(4)*4
f_34 = d_34+e_34
print(f_34)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[9. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0.]
 [0. 0. 9. 0. 0.]
 [0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 9.]]
[[5. 1. 1. 1.]
 [1. 5. 1. 1.]
 [1. 1. 5. 1.]
 [1. 1. 1. 5.]]


In [55]:
import numpy as np
print('aku akan meng copy matriks yaitu')
e_34 = np.array([2,6,7,8,3,5,9,])
print(e_34)
c_34 = e_34.copy()
print(c_34)

aku akan meng copy matriks yaitu
[2 6 7 8 3 5 9]
[2 6 7 8 3 5 9]


In [59]:
import numpy as np
a_34 = np.array([2,6,7,9,4,5])
b_34 = np.array([3,4,5,7,9,2])
hasil = a_34 + b_34
print(hasil)
hasil = a_34 - b_34
print(hasil)
hasil = a_34 * b_34
print(hasil)
hasil = a_34 / b_34
hasil = a_34 **2
print(hasil)



[ 5 10 12 16 13  7]
[-1  2  2  2 -5  3]
[ 6 24 35 63 36 10]
[ 4 36 49 81 16 25]


In [78]:
import numpy as np
b_34 = np.array([2,4,8,10,12])
sum(b_34)




36